# Generated by Django 3.1.3 on 2021-10-23 10:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-4.png', upload_to=account.models.get_image_path),
        ),
    ]
