# Generated by Django 3.1.3 on 2021-10-25 15:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211026_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-2.png', upload_to=account.models.get_image_path),
        ),
    ]
