# Generated by Django 3.1.3 on 2020-11-04 05:27

import api.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201103_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to=api.models.Movie_image_path),
        ),
    ]
