# Generated by Django 3.1.3 on 2020-11-06 03:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201104_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesimage',
            name='image',
            field=models.ImageField(upload_to=api.models.Movie_image_path),
        ),
    ]
