# Generated by Django 3.1.3 on 2020-11-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201106_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created']},
        ),
    ]
