# Generated by Django 3.1.3 on 2021-02-04 00:18

from django.db import migrations, models
import sleeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeker', '0002_auto_20210204_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeker',
            name='image',
            field=models.ImageField(default='default.png', upload_to=sleeker.models.get_image_path),
        ),
    ]
