# Generated by Django 3.1.3 on 2021-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeker', '0003_auto_20210204_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeker',
            name='image',
            field=models.TextField(max_length=2000),
        ),
    ]
