# Generated by Django 3.1.3 on 2021-10-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdbID',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Poster',
            new_name='poster',
        ),
    ]
